name: "CF CLI Action"
description: "Deploy and manage Cloud Foundry using the cf cli"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  cf_api:
    description: "Target API Endpoint of Cloud Foundry"
    required: true
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target Organization"
    required: false
  cf_space:
    description: "Target Space"
    required: false
  command:
    description: "Command to run using CF CLI"
    required: true
  retries:
    description: "Number of retries that should be attempted"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Setup cf8 CLI"
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates jq wget gpg
        sudo wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
        sudo echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf8-cli
      shell: bash
    - name: "Execute entrypoint.sh"
      run: |
        ${{inputs}}
        ${GITHUB_ACTION_PATH}/entrypoint.sh ${{ inputs.command }}
      shell: bash
