name: "CF CLI Action"
description: "Deploy and manage Cloud Foundry using the cf cli"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  cf_api:
    description: "Target API Endpoint of Cloud Foundry"
    required: true
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_org:
    description: "Target Organization"
    required: false
  cf_space:
    description: "Target Space"
    required: false
  command:
    description: "Command to run using CF CLI"
    required: true
  retries:
    description: "Number of retries that should be attempted"
    required: false
  skip_ssl_validation:
    description: "Skip SSL Validation"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Setup cf8 CLI"
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        wget 'https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.13.0&source=github-rel' --output-document cf8-cli.tgz
        tar -xvzf cf8-cli.tgz
        sudo install cf8 /usr/bin
    - name: "Execute entrypoint.sh"
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/entrypoint.sh '${{ toJSON(inputs) }}'
