name: Test CF CLI Action

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/cf-cli
      with:
        cf_api: ${{ secrets.CF_API }}
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_ORG }}
        cf_space: ${{ secrets.CF_SPACE }}
        command: target
        retries: 4